export const FINDAHARP_PRODUCTS = [
        {
            id: "VNHP-ZBYT",
            store: 'findaharp',
            artist_first: 'Gioachino',
            artist_last: 'Rossini',
            category: 'music',
            subcategories: ['all ensemble','violin/harp'],
            title: "Andante con Variazioni for violin and harp", 
            price: 3.00, 
            newprice: '',
            condition: '7',
            level: 'advanced',
            harptype: 'Pedal',
            notes: 'Some yellowing around edges. No markings.',
            image: "../../../img/store/findaharp/sheetmusic/rossiniandante.jpg", 
            description: "edited by Amedeo Cerasa.",
            newused: 'used'
        },
        {
            id: 'RVVC-XIUY',
            store: 'findaharp',
            category: 'music',
            subcategories: ['all ensemble','voice/harp'],
            title: "5 Popular Greek Melodies for voice and harp", 
            artist_first: "Maurice",
            artist_last: "Ravel/Salzedo",
            price: '7.00', 
            newprice: '',
            condition: '9',
            level: 'advanced',
            harptype: 'pedal',
            newprice: '15.00',
            notes: 'Good shape. No markings. Small water mark in upper l.h. corner.',
            image: "../../../img/store/findaharp/sheetmusic/ravelgreek.jpg", 
            description: "A hidden gem. Rarely played, stunning work by Ravel. 5 short melodies from the folk tradition.",
            newused: 'used'
        },
        {
            id: 'KrFl-TPNQ',
            store: 'findaharp',
            category: 'music',
            subcategories: ['all ensemble','flute/harp'], 
            title: "Sonata No. III for flute (or violin) and harp", 
            artist_first: "Jean-Baptiste",
            artist_last: "Krumpholz/Avesian",
            price: '7.00', 
            newprice: '',
            condition: '10',
            level: 'int-adv',
            harptype: 'pedal',
            newprice: '14.00',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/krumpholzsonata3.jpg", 
            description: "Great for setting a classical, sophisticated atmosphere.",
            newused: 'used'
        },
        {
            id: 'WdQn-AFNR',
            store: 'findaharp',
            category: 'music',
            subcategories: ['all ensemble','other ensembles'], 
            title: "Three Wedding Marches for woodwind quintermediateet and harp.", 
            artist_first: "",
            artist_last: "Wagner, Mozart, Mendelssohn",
            price: '10.00', 
            newprice: '',
            condition: '9',
            level: 'intermediate',
            harptype: 'pedal',
            newprice: '25.00',
            notes: 'Like brand new inside. Slightly worn on cover (see photo).',
            image: "../../../img/store/findaharp/sheetmusic/weddingmarchesquintet.jpg", 
            description: 'Mozart, March from "Marriage of Figaro"; Wagner, Bridal Chorus from "Lohengrin" (Here Comes the Bride); Mendelssohn, Wedding March from "A Mid-Summer Nights Dream". Arranged by Ryohel Nakagawa.',
            newused: 'used'
        },
        {
            id: 'HovA-KZXD',
            store: 'findaharp',
            category: 'music',
            subcategories: ['all ensemble','flute/harp'], 
            title: "Garden of Adonis for flute and harp (or piano)", 
            artist_first: "Alan",
            artist_last: "Hovaness",
            price: '13.00', 
            newprice: '',
            condition: '7',
            level: 'advanced',
            harptype: 'Pedal',
            newprice: '25.00',
            notes: 'A few markings in harp part. Many markings in flute part. Otherwise excellent condition.',
            image: "../../../img/store/findaharp/sheetmusic/hovanessadonis.jpg", 
            description: 'Beautiful, sweeping, sophisticated recital piece for flute and harp.',
            newused: 'used'
        },
        {
            id: 'MzCr-FBAE',
            store: 'findaharp',
            category: 'music',
            subcategories: ['harp solo'],
            title: "Christmas Harpist", 
            artist_first: "Marylyn",
            artist_last: "Marzuki",
            price: '5.00',
            newprice: '', 
            condition: '6',
            level: 'Beg-Int',
            harptype: 'pedal',
            newprice: '12.95',
            notes: 'Some markings. Some yellowing from age.',
            image: "../../../img/store/findaharp/sheetmusic/christmasharpist.jpg", 
            description: "Beautiful Christmas arrangements for pedal harp.",
            newused: 'used'
        },
        {
            id: 'Pach-XWMJ',
            store: 'findaharp',
            category: 'music', 
            subcategories: ['all ensemble','violin/harp','flute/harp','harp ensemble'],
            title: "Canon in D for harp solo or duet", 
            artist_first: "Johann",
            artist_last: "Pachelbel/Woods",
            price: '5.00', 
            newprice: '',
            condition: '8',
            level: 'intermediate',
            harptype: 'lever',
            notes: 'Like new. No markings.',
            image: "../../../img/store/findaharp/sheetmusic/canonind.jpg", 
            description: "Versatile arrangement of a classic. Can be played as a solo or with a 2nd harp or with flute or violin.",
            newused: 'used'
        },
        {
            id: 'Wald-PVBI',
            store: 'findaharp',
            category: 'music', 
            subcategories: ['harp solo', 'pop'],
            title: "Tea at the Waldorf", 
            artist_first: "Ray",
            artist_last: "Pool",
            price: '13.50', 
            newprice: '19.50',
            condition: '10',
            level: 'advanced',
            harptype: 'Pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/Tea.jpg", 
            description: "Imaginative and enjoyable arrangements. A staple for the gigging harpist.",
            newused: 'used'
        },
        {
            id: 'West-JDXL',
            store: 'findaharp',
            category: 'music', 
            subcategories: ['harp solo', 'pop'],
            title: "Into the West from Lord of the Rings", 
            artist_first: "Sylvia",
            artist_last: "Woods",
            price: '5.00', 
            newprice: '',
            condition: '8',
            level: 'beginning',
            harptype: 'lever',
            notes: 'A couple of markings. Otherwise excellent.',
            image: "../../../img/store/findaharp/sheetmusic/IntoWest.jpg", 
            description: "Easy and Intermediate versions. Beautiful melody.",
            newused: 'used'
        },
        {
            id: 'FrEx-DCUJ',
            store: 'findaharp',
            category: 'music', 
            subcategories: ['harp solo', 'exercises'],
            title: "Harp Excercises for Speed and Agility", 
            artist_first: "Deborah",
            artist_last: "Friou",
            price: '12.00', 
            newprice: '',
            condition: '8',
            level: 'intermediate',
            harptype: 'lever',
            notes: 'A few markings. Otherwise excellent.',
            image: "../../../img/store/findaharp/sheetmusic/Agility.jpg", 
            description: "Excellent exercise book.",
            newused: 'used'
        },
        {
            id: 'Disw-NBSV',
            store: 'findaharp',
            category: 'music', 
            subcategories: ['harp solo', 'pop'],
            title: "76 Disney Songs for the Harp", 
            artist_first: "Sylvia",
            artist_last: "Woods",
            price: '25.00', 
            newprice: '36.95',
            condition: '8',
            level: 'intermediate',
            harptype: 'lever',
            notes: 'A few markings. Otherwise excellent.',
            image: "../../../img/store/findaharp/sheetmusic/Disney.jpg", 
            description: "What a great book! Part of Your World, Be Our Guest, A Whole New World, Winnie the Pooh and many, many more.",
            newused: 'used'
        },
        {
            id: "CrWd-VONT",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['Christmas','harp solo'],
            title: "50 Christmas Carols for All Harps", 
            artist_first: "Sylvia",
            artist_last: "Woods",
            price: "13.00", 
            newprice: "19.95",
            condition: "9",
            level: "beg-int",
            harptype: "lever",
            notes: "A couple of markings.",
            image: "../../../img/store/findaharp/sheetmusic/50Christmas.jpg", 
            description: "A must have for a gigging harpist. A fun book for a hobbyist. Each carol is arranged in an easy version and an intermediate version.",
            newused: 'used'
        },
        {
            id: "Cur3-SCYE",
            category: 'music', 
            subcategories: ['methods'],
            title: "Student Harpist, level 3", 
            artist_first: "Stephanie",
            artist_last: "Curcio",
            price: '6.00', 
            newprice: '12.00',
            condition: '7',
            level: 'int-adv',
            harptype: 'pedal',
            notes: 'Cover shows some age. Inside is like new.',
            image: "../../../img/store/findaharp/sheetmusic/Curcio3.jpg", 
            description: "",
            newused: 'used'
        },
        {
            id: "Cur3-XCCX",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['methods'],
            title: "Student Harpist, level 2", 
            artist_first: "Stephanie",
            artist_last: "Curcio2",
            price: '3.00', 
            newprice: '12.00',
            condition: '3',
            level: 'int-advanced',
            harptype: 'pedal',
            notes: 'Cover shows some age. Many markings inside. Some exercises completed.',
            image: "../../../img/store/findaharp/sheetmusic/Curcio2.jpg", 
            description: "",
            newused: 'used'
        },
        {
            id: "RaFH-JVWR",
            category: 'music', 
            subcategories: ['collections', 'methods'],
            title: "Making Music for Folk Harp", 
            artist_first: "Susan",
            artist_last: "Raimond",
            price: '9.00', 
            newprice: '14.99',
            condition: '10',
            level: 'beginning',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/RaimondFH.jpg", 
            description: "Simple tunes for the Folk Harp. Comes with CD.",
            newused: 'used'
        },
        {
            id: "Rily-BUQU",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['methods'],
            title: "Basic Harp for Beginners", 
            artist_first: "Laura",
            artist_last: "Riley",
            price: '10.00', 
            newprice: '14.99',
            condition: '10',
            level: 'beginning',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/RileyBasicHarp.jpg", 
            description: "Instructional book starting from the very beginning.",
            newused: 'used'
        },
        {
            id: "RdCr-KZOH",
            category: 'music', 
            subcategories: ['Christmas','collection','harp solo'],
            title: "A Carol Collection", 
            artist_first: "Mary",
            artist_last: "Radspinner",
            price: '2.00', 
            newprice: '5.00',
            condition: '9',
            level: 'intermediate',
            harptype: 'all',
            notes: 'No markings. Like new.',
            image: "../../../img/store/findaharp/sheetmusic/Carols.jpg", 
            description: "6 Carols arranged for all harps.",
            newused: 'used'
        },
        {
            id: "WhLv-FCBA",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['harp solo','pop'],
            title: "Where is Love", 
            artist_first: "Carol",
            artist_last: "Robbins",
            price: '4.00', 
            newprice: '6.00',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new. Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/WhereLove.jpg", 
            description: "",
            newused: 'used'
        },
        {
            id: "KlEx-ZHQN",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['excercises'],
            title: "20 Melodic Studies, vol 1, For All Harps", 
            artist_first: "Cindy",
            artist_last: "Kleinstuber",
            price: '3.00', 
            newprice: '',
            condition: '8',
            level: 'beg-int',
            harptype: 'all',
            notes: 'Some fading on the cover. Inside brand new.',
            image: "../../../img/store/findaharp/sheetmusic/Klein1.jpg", 
            description: "Reinforces basic techniques of intervals and arpeggios.",
            newused: 'used'
        },
        {
            id: "BtRb-LJZG",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['harp solo','pop'],
            title: "But Not For Me", 
            artist_first: "Carol",
            artist_last: "Robbins",
            price: '3.00', 
            newprice: '5.00',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/ButNotForMe.jpg", 
            description: "Jazzy, full chords, lots of pedals, but worth it!! Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.",
            newused: 'used'
        },
        {
            id: "RnBw-TIGT",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop', 'harp solo'],
            title: "I'm Always Chasing Rainbows", 
            artist_first: "Penny Howk",
            artist_last: "Beavers",
            price: '1.00', 
            newprice: '5.00',
            condition: '5',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Mistake in title on cover. Cover reads "Forever" instead of "Always". Inside like brand new. Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/Rainbows.jpg", 
            description: "An excellent arrangement.",
            newused: 'used'
        },
        {
            id: "BeWt-PRWK",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop','harp solo'],
            title: "Bewitched", 
            artist_first: "Paul",
            artist_last: "Baker",
            price: '2.00', 
            newprice: '5.50',
            condition: '6',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Light smudges on cover. Inside like brand new. Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/Bewitched.jpg", 
            description: "Paul Baker is an excellent arranger.",
            newused: 'used'
        },
        {
            id: "MnRv-PPYT",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop', 'harp solo'],
            title: "Moon River", 
            artist_first: "Paul",
            artist_last: "Baker",
            price: '3.00', 
            newprice: '5.50',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/MoonRiver.jpg", 
            description: "Paul Baker is an excellent arranger!",
            newused: 'used'
        },
        {
            id: "AnWz-GPVY",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['harp solo','pop'],
            title: "Anniversary Waltz", 
            artist_first: "Deborah",
            artist_last: "Henson-Conant",
            price: '1.00', 
            newprice: '4.00',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/AnniversaryWaltz.jpg", 
            description: "",
            newused: 'used'
        },
        {
            id: "HdGv-OTUG",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['classical','harp solo'],
            title: "Gavotte from 'Semele'", 
            artist_first: "G.F.",
            artist_last: "Handel/Schuman",
            price: '3.00', 
            newprice: '',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/Gavotte.jpg", 
            description: "Arranged by Ellis Schuman.",
            newused: 'used'
        },
        {
            id: "FsPt-ZLME",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['harp solo','collections'],
            title: "Forest Pathways", 
            artist_first: "Dewey",
            artist_last: "Owens",
            price: '17.00', 
            newprice: '25.25',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/ForestPathways.jpg", 
            description: "A collection of Meditative Pieces arranged for pedal harp by Dewey Owens.",
            newused: 'used'
        },
        {
            id: "HnWh-MPIH",
            category: 'music',
            store: 'findaharp', 
            subcategories: ['harp solo', 'wedding', 'classical'],
            title: "Where'er You Walk", 
            artist_first: "G.F.",
            artist_last: "Handel/Burton",
            price: '4.00', 
            newprice: '7.70',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/WhereWalk.jpg", 
            description: "",
            newused: 'used'
        },
        {
            id: "HnPr-BTHA",
            category: 'music', 
            store: 'findaharp',
            subcategories: ['classical','harp solo','wedding'],
            title: "Praise be to Thee", 
            artist_first: "G.F.",
            artist_last: "Handel",
            price: 'free with purchase', 
            newprice: '3.50',
            condition: '7',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Where on cover. Only 2 pages long.',
            image: "../../../img/store/findaharp/sheetmusic/PraiseBe.jpg", 
            description: "",
            newused: 'used'
        },
        {
            id: "HnCr-SLOA",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['classical','wedding','harp solo'],
            title: "Two Sinfonias from 'Saul'", 
            artist_first: "G.F.",
            artist_last: "Handel/Schuman",
            price: '3.00', 
            newprice: '',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/SaulSinfonias.jpg", 
            description: "",
            newused: 'used'
        },
        {
            id: "TrAr-JBOD",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['harp solo','folk'],
            title: "Three Traditional Airs", 
            artist_first: "Sheila",
            artist_last: "Larchet-Cuthbert",
            price: '3.00', 
            newprice: '',
            condition: '9',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Slight wear on cover. Inside brand new.',
            image: "../../../img/store/findaharp/sheetmusic/AncientAirs.jpg", 
            description: "Arranged by John F. Larchet. Transcribed for concert harp by Sheila Larchet Cuthbert.",
            newused: 'used'
        },
        {
            id: "RtSn-DHTK",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['classical','all ensemble','flute/harp'],
            title: "Sonata", 
            artist_first: "Nino",
            artist_last: "Rota",
            price: '13.00', 
            newprice: '18.00',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/RotaSonata.jpg", 
            description: "",
            newused: 'used'
        },
        {
            id: "RdSn-MLQG",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['concerto','classical'],
            title: "Concierto Serenata", 
            artist_first: "Joaquin",
            artist_last: "Rodrigo",
            price: '20.00', 
            newprice: '70.00',
            condition: '9',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Slight wear on cover. Like brand new inside. Amazon listed this new at $70.00, but might be a better new price elsewhere.',
            image: "../../../img/store/findaharp/sheetmusic/RodSeren.jpg", 
            description: "",
            newused: 'used'
        },
        {
            id: "WrPd-BKXK",
            store: 'findaharp',
            store: 'findaharp',
            category: 'music', 
            subcategories: ['books'],
            title: "Writing for the Pedal Harp", 
            artist_first: "Ruth K.",
            artist_last: "Inglefield",
            price: '18.00', 
            newprice: '25.00',
            condition: '10',
            level: '',
            harptype: 'pedal',
            notes: 'Like Brand New',
            image: "../../../img/store/findaharp/sheetmusic/InglefieldPedal.jpg", 
            description: "A Standardized Maual for Composers and Harpists",
            newused: 'used'
        },
        {
            id: "SwGd-UAIV",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['books'],
            title: "Guide For Harpists", 
            artist_first: "Carl",
            artist_last: "Swanson",
            price: '9.00', 
            newprice: '16.00',
            condition: '7',
            level: 'beginning',
            harptype: 'pedal',
            notes: 'Fading on the cover. No markings. Good inside.',
            image: "../../../img/store/findaharp/sheetmusic/SwansonGuide.jpg", 
            description: "An excellent resource.",
            newused: 'used'
        },
        {
            id: "BrCl-RDWF",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop', 'harp solo', 'collections'],
            title: "By Popular Demand, Favourite Standards", 
            artist_first: "Barbara",
            artist_last: "Brundage",
            price: '13.00', 
            newprice: '18.00',
            condition: '10',
            level: 'advanced',
            harptype: 'lever',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/ByPopularStandards.jpg", 
            description: "Misty, Night and Day, Star Dust, and more",
            newused: 'used'
        },
        {
            id: "PlPp-OXZH",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop','collections','harp solo'],
            title: "American Classic Pop, 12 Broadway Standards", 
            artist_first: "Ray",
            artist_last: "Pool",
            price: '18.00', 
            newprice: '24.00',
            condition: '10',
            level: 'advanced',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/AmericanClassicPopBroadway.jpg", 
            description: "Love Walked In, My Funny Valentine, People and more",
            newused: 'used'
        },
        {
            id: "PlPp-GYGL",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop','collections','harp solo'],
            title: "American Classic Pop, vol 2, Songs of George and Ira Gershwin", 
            artist_first: "Ray",
            artist_last: "Pool",
            price: '18.00', 
            newprice: '24.00',
            condition: '10',
            level: 'advanced',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/AmericanClassicPop.jpg", 
            description: "But Not For Me, Embraceable You, I Got Rhythm, and more",
            newused: 'used'
        },
        {
            id: "BrLv-HNLT",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['harp solo', 'collections', 'pop'],
            title: "Popular Contemporary Love Songs for Harp", 
            artist_first: "Daniel",
            artist_last: "Burton",
            price: '7.00', 
            newprice: '11.00',
            condition: '10',
            level: 'int-adv',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/BurtonLove.jpg", 
            description: "Wind Beneath My Wings, The Rose, Evergreen, Sunrise Sunset",
            newused: 'used'
        },
        {
            id: "GrBk-IFCH",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['all ensemble', 'flute/harp','pop', 'voice/harp', 'other ensembles'],
            title: "A Gershwin Sampler", 
            artist_first: "George",
            artist_last: "Gershwin/Baker",
            price: '22.00', 
            newprice: '28.00',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/GershwinSampler.jpg", 
            description: "A medley of Gershwin tunes from Rhapsody in Blue, American in Paris, But Not For Me, Embraceable You, and more",
            newused: 'used'
        },
        {
            id: "BWHK-PXWD",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['inspirational','harp solo'],
            title: "Harp and the King, The", 
            artist_first: "Debbie",
            artist_last: "Brewin-Wilson",
            price: '5.00', 
            newprice: '',
            condition: '10',
            level: 'intermediate',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/HarpofmyKing.jpg", 
            description: "Celtic tunes old and new for Christian Worship",
            newused: 'used'
        },
        {
            id: "McHk-RIBZ",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['harp solo','classical','collections'],
            title: "Haiku for Harp", 
            artist_first: "Susann",
            artist_last: "McDonald/Linda Wood",
            price: '12.00', 
            newprice: '20.00',
            condition: '7',
            level: 'beginning',
            harptype: 'pedal',
            notes: 'Some water marks on cover and first page. No markings. The rest is good.',
            image: "../../../img/store/findaharp/sheetmusic/Haiku.jpg", 
            description: "12 pieces that teach modern techniques such as pedal buzzes, fingernail glisses and changing meter.",
            newused: 'used'
        },
        {
            id: "MsFl-VTUC",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['all ensemble', 'flute/harp','collections'],
            title: "Flute and Harp Delights, vol 1", 
            artist_first: "Patty",
            artist_last: "Masri-Fletcher",
            price: '6.50', 
            newprice: '13.00',
            condition: '7',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Upper right corner is bent. No markings. Inside excellent.',
            image: "../../../img/store/findaharp/sheetmusic/MasriV1.jpg", 
            description: "O Mio Bambino, The Swan, and more",
            newused: 'used'
        },
        {
            id: "WtAn-OLQN",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['classical','harp solo','collections'],
            title: "Anthology of English Music for the Harp, vol. 1 1550-1650", 
            artist_first: "David",
            artist_last: "Watkins",
            price: '18.00', 
            newprice: '31.00',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/WatkinsV1.jpg", 
            description: "Farnaby, Morley, Byrd, Bull, and more",
            newused: 'used'
        },
        {
            id: "ClTr-KVGM",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop','harp solo'],
            title: "Not for Harp, Tears in Heaven", 
            artist_first: "Eric",
            artist_last: "z-Clapton",
            price: 'free with purchase', 
            newprice: '',
            condition: '10',
            level: 'advanced',
            harptype: 'not for harp',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/Tears.jpg", 
            description: "NOT HARP MUSIC, piano/vocal/guitar",
            newused: 'used'
        },
        {
            id: "ShTh-ppqx",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['ensemble', 'other'],
            title: "Theseus for Harp and String Quartet", 
            artist_first: "Murray",
            artist_last: "Schafer",
            price: '20.00', 
            newprice: '50.00',
            condition: '8',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Cover slightly worn. Inside like new.',
            image: "../../../img/store/findaharp/sheetmusic/Theseus.jpg", 
            description: "Score only. Juno award nominee. Commissioned by Judy Loman of the Toronto Symphony.",
            newused: 'used'
        },
        {
            id: "RlCl-ggrs",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['classical'],
            title: "Not for Harp, Most Relaxing Classical Music Ever", 
            artist_first: "",
            artist_last: "z-various",
            price: '15.00', 
            newprice: '45.00',
            condition: '10',
            level: 'advanced',
            harptype: 'not for harp',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/pianoclassics.jpg", 
            description: "Not For Harp. This is a piano book. Beethoven, Bach, Handel, Debussy, Mozart, and More",
            newused: 'used'
        },
        {
            id: "NaSn-nhev",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['classical'],
            title: "Sonatina", 
            artist_first: "Sergiu",
            artist_last: "Natra",
            price: '20.00', 
            newprice: '30.00',
            condition: '9',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Slight bend in upper right corner. Otherwise, like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/NatraSonatina.jpg", 
            description: "A classic of the 20th century harp repertoire.",
            newused: 'used'
        },
        {
            id: "UlCh-axoe",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['Christmas'],
            title: "Not for Harp, Ultimate Christmas Fake Book", 
            artist_first: "Hal",
            artist_last: "z-Leonard Publications",
            price: '20.00', 
            newprice: '30.00',
            condition: '7',
            level: 'advanced',
            harptype: 'not for harp',
            notes: 'Cover slightly worn. Slight yellowing on pages.',
            image: "../../../img/store/findaharp/sheetmusic/ChristmasFake.jpg", 
            description: "Piano/Vocal/Guitar Over 140 Christmas Songs.",
            newused: 'used'
        },
        {
            id: "OrSl-zrkq",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['classical','solo'],
            title: "Variations on a Chant", 
            artist_first: "Juan",
            artist_last: "Orrego-Salas",
            price: '5.00', 
            newprice: '10.50',
            condition: '6',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Cover weathered around the edges. Inside is fine.',
            image: "../../../img/store/findaharp/sheetmusic/OrregoSalas.jpg", 
            description: "Commissioned by the World Harp Congress, Jerusalem 1986",
            newused: 'used'
        },
        {
            id: "BlDs-pjfz",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop'],
            title: "Besto of Disney", 
            artist_first: "Suzanne",
            artist_last: "Balderston",
            price: '12.00', 
            newprice: '20.00',
            condition: '9',
            level: 'beg-int',
            harptype: 'all',
            notes: 'Like new',
            image: "../../../img/store/findaharp/sheetmusic/BestDisney.jpg", 
            description: "Part of Your World, When You Wish Upon a Star, Some Day My Prince Will Come and More!",
            newused: 'used'
        },
        {
            id: "LfLv-ialh",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop'],
            title: "Not For Harp", 
            artist_first: "Zorro",
            artist_last: "z-Movie",
            price: 'free with purchase', 
            newprice: '',
            condition: '8',
            level: 'advanced',
            harptype: 'not for harp',
            notes: 'Some wearing on cover. Inside clean',
            image: "../../../img/store/findaharp/sheetmusic/Zorro.jpg", 
            description: "Not for Harp. Pno/vocal/guitar",
            newused: 'used'
        },
        {
            id: "ImRo-erzi",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['classical', 'solo'],
            title: "Impromptu", 
            artist_first: "Albert",
            artist_last: "Roussel",
            price: '3.00', 
            newprice: '5.00',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/Impromptu.jpg", 
            description: "",
            newused: 'used'
        },
        {
            id: "PnBs-vlun",
            store: 'findaharp',
            category: 'music', 
            subcategories: [],
            title: "Not for Harp, Piano Basics", 
            artist_first: "James",
            artist_last: "z-Bastien",
            price: '5.00', 
            newprice: '8.50',
            condition: '7',
            level: 'beginning',
            harptype: 'not for harp',
            notes: 'Some markings first five pages.',
            image: "../../../img/store/findaharp/sheetmusic/BegPiano.jpg", 
            description: "Primer Level",
            newused: 'used'
        },
        {
            id: "TcSg-pcto",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop'],
            title: "Not for Harp Torch Songs", 
            artist_first: "Hal",
            artist_last: "z-Leonard Publications",
            price: '12.00', 
            newprice: '20.00',
            condition: '9',
            level: 'advanced',
            harptype: 'Not for Harp',
            notes: 'Like new',
            image: "../../../img/store/findaharp/sheetmusic/TorchSongs.jpg", 
            description: "244 pages! A big collection of Sultry Jazz and Big Band standards.",
            newused: 'used'
        },
        {
            id: "SmAn-blyw",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop'],
            title: "Angel", 
            artist_first: "Sarah",
            artist_last: "McLachlan",
            price: '5.00', 
            newprice: '7.00',
            condition: '10',
            level: 'beg-int',
            harptype: 'all',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/Angel.jpg", 
            description: "Paul Baker is an excellent arranger.",
            newused: 'used'
        },
        {
            id: "BcBr-pcto",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['classical','solo'],
            title: "Two J.S.Bach Arrangements", 
            artist_first: "Daniel",
            artist_last: "Burton",
            price: '3.00', 
            newprice: '6.00',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like new',
            image: "../../../img/store/findaharp/sheetmusic/TwoBach.jpg", 
            description: "Jesu, Joy of Man's DesiringGod's Time is Best",
            newused: 'used'
        },
        {
            id: "DyLf-pcto",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop'],
            title: "A Day in the Life", 
            artist_first: "Paul",
            artist_last: "Baker",
            price: '3.00', 
            newprice: '',
            condition: '10',
            level: 'advanced',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/DayLife.jpg", 
            description: "Paul Baker is an excellent arranger.",
            newused: 'used'
        },
        {
            id: "OnTm-bipb",
            store: 'findaharp',
            category: 'music', 
            subcategories: ['pop'],
            title: "Only Time", 
            artist_first: "",
            artist_last: "Enya/David Ice",
            price: '3.00', 
            newprice: '',
            condition: '10',
            level: 'intermediate',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/OnlyTime.jpg", 
            description: "",
            newused: 'used'
        },
        {
            id: '-apmt',
            store: 'findaharp',
            category: 'accessories',
            title: "Test Item", 
            artist: "",
            harptype: "",
            price: '1.50',
            newprice: '',
            image: "../../../img/factoryFloor.jpg", 
            description: "This item is included for testing the strore functionality. Please choose credit card payment and use the following card: '4242 4242 4242 4242 exp. 04/24 CVC 242 zip 42424",
            newused: 'used'
        },
        {
            id: "QAFT-WQDN",
            store: 'findaharp',
            category: 'cds',
            subcategories: ['inspirational'],
            title: "A Quiet Afternoon", 
            artist_first: "Tisha",
            artist_last: "Murvihill",
            price: '15.00',
            image: "../../../img/store/findaharp/cds/QuietAfternoon.jpg", 
            description: "Winner, Instrumental Album of the Year, Gospel Music Association of Canada. Fourteen beautiful arrangements of some of our most beautiful worship melodies, including: I Exalt Thee; Oh, How He Loves You and Me; Fairest Lord Jesus; As the Deer; Jesus, Name Above All Names.",
            newused: 'new'
        },
        {
            id: 'BRWR-BIKF',
            store: 'findaharp',
            category: 'cds', 
            subcategories: ['classical'],
            title: "If Brahms Wrote For Harp", 
            artist_first: "Tisha",
            artist_last: "Murvihill",
            price: 15.00,
            image: "../../../img/store/findaharp/cds/IfBrahmsWrote.jpg", 
            description: "“Stunning Presentation of the music of Johannes Brahms” - The HarpColumn - Eleven Intermezzi and a Rhapsody Arranged and performed by Tisha Murvihill, Calgary Philharmonic Orchestra Principal Harp.",
            newused: 'new'
        },
        {
            id: 'JustAs-NUAA',
            store: 'findaharp',
            category: 'cds', 
            title: "Come Just As You Are", 
            subcategories: ['inspirational'], 
            artist_first: "Tisha",
            artist_last: "Murvihill",
            price: 15.00,
            image: "../../../img/store/findaharp/cds/ComeJustAs.webp", 
            description: "Come Just As You Are is a follow-up CD to Tisha’s award winning CD, A Quiet Afternoon. The CD features 14 inspirational praise and worship songs including Amazing Grace, Draw Me Close to You, Lord Be Glorified, and You Are My All in All.",
            newused: 'new'
        },
    ]   
