import uuid from 'react-uuid';
export const FINDAHARP_PRODUCTS = [
        {
            id: "QAFT-WQDN",
            category: 'cds',
            subCategory: ['inspirational'],
            title: "A Quiet Afternoon", 
            artist_first: "Tisha",
            artist_last: "Murvihill",
            price: '15.00',
            image: "../../../img/store/findaharp/cds/QuietAfternoon.jpg", 
            description: "Winner, Instrumental Album of the Year, Gospel Music Association of Canada. Fourteen beautiful arrangements of some of our most beautiful worship melodies, including: I Exalt Thee; Oh, How He Loves You and Me; Fairest Lord Jesus; As the Deer; Jesus, Name Above All Names."
        },
        {
            id: 'BRWR-BIKF',
            category: 'cds', 
            subCategory: ['classical'],
            title: "If Brahms Wrote For Harp", 
            artist_first: "Tisha",
            artist_last: "Murvihill",
            price: 15.00,
            image: "../../../img/store/findaharp/cds/IfBrahmsWrote.jpg", 
            description: "“Stunning Presentation of the music of Johannes Brahms” - The HarpColumn - Eleven Intermezzi and a Rhapsody Arranged and performed by Tisha Murvihill, Calgary Philharmonic Orchestra Principal Harp."
        },
        {
            id: 'JustAs-NUAA',
            category: 'cds', 
            title: "Come Just As You Are", 
            subCategory: ['inspirational'], 
            artist_first: "Tisha",
            artist_last: "Murvihill",
            price: 15.00,
            image: "../../../img/store/findaharp/cds/ComeJustAs.webp", 
            description: "Come Just As You Are is a follow-up CD to Tisha’s award winning CD, A Quiet Afternoon. The CD features 14 inspirational praise and worship songs including Amazing Grace, Draw Me Close to You, Lord Be Glorified, and You Are My All in All."
        },
        // {
        //     id: uuid(),
        //     category: 'cd',
        //     title: "Live Test Item", 
        //     artist: "",
        //     price: '1.50',
            // newprice: '',
        //     image: "../../../img/factoryFloor.jpg", 
        //     description: "This item is included for testing the strore functionality. Please choose credit card payment and use the following card: '4242 4242 4242 4242 exp. 04/24 CVC 242 zip 42424"
        // },
        {
            id: "VNHP-ZBYT",
            artist_first: 'Gioachino',
            artist_last: 'Rossini',
            category: 'music',
            subCategory: ['ensemble'],
            title: "Andante con Variationi for violin and harp", 
            price: 3.00, 
            newprice: '',
            condition: '7',
            level: 'Adv',
            harptype: 'Pedal',
            notes: 'Some yellowing around edges. No markings.',
            image: "../../../img/store/findaharp/sheetmusic/rossiniandante.jpg", 
            description: "edited by Amedeo Cerasa."
        },
        {
            id: 'RVVC-XIUY',
            category: 'music',
            subCategory: ['ensemble'],
            title: "5 Popular Greek Melodies for voice and harp", 
            artist_first: "Maurice",
            artist_last: "Ravel/Salzedo",
            price: '7.00', 
            newprice: '',
            condition: '9',
            level: 'Adv',
            harptype: 'pedal',
            newprice: '15.00',
            notes: 'Good shape. No markings. Small water mark in upper l.h. corner.',
            image: "../../../img/store/findaharp/sheetmusic/ravelgreek.jpg", 
            description: "A hidden gem. Rarely played, stunning work by Ravel. 5 short melodies from the folk tradition."
        },
        {
            id: 'KrFl-TPNQ',
            category: 'music',
            subCategory: ['ensemble'], 
            title: "Sonata No. III for flute (or violin) and harp", 
            artist_first: "Jean-Baptiste",
            artist_last: "Krumpholz/Avesian",
            price: '7.00', 
            newprice: '',
            condition: '10',
            level: 'Int-Adv',
            harptype: 'pedal',
            newprice: '14.00',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/krumpholzsonata3.jpg", 
            description: "Great for setting a classical, sophisticated atmosphere."
        },
        {
            id: 'WdQn-AFNR',
            category: 'music',
            subCategory: ['ensemble'], 
            title: "Three Wedding Marches for woodwind quintet and harp.", 
            artist_first: "",
            artist_last: "Wagner, Mozart, Mendelssohn",
            price: '10.00', 
            newprice: '',
            condition: '9',
            level: 'Int',
            harptype: 'pedal',
            newprice: '25.00',
            notes: 'Like brand new inside. Slightly worn on cover (see photo).',
            image: "../../../img/store/findaharp/sheetmusic/weddingmarchesquintet.jpg", 
            description: 'Mozart, March from "Marriage of Figaro"; Wagner, Bridal Chorus from "Lohengrin" (Here Comes the Bride); Mendelssohn, Wedding March from "A Mid-Summer Nights Dream". Arranged by Ryohel Nakagawa.'
        },
        {
            id: 'HovA-KZXD',
            category: 'music',
            subCategory: ['ensemble'], 
            title: "Garden of Adonis for flute and harp (or piano)", 
            artist_first: "Alan",
            artist_last: "Hovaness",
            price: '13.00', 
            newprice: '',
            condition: '7',
            level: 'Adv',
            harptype: 'Pedal',
            newprice: '25.00',
            notes: 'A few markings in harp part. Many markings in flute part. Otherwise excellent condition.',
            image: "../../../img/store/findaharp/sheetmusic/hovanessadonis.jpg", 
            description: 'Beautiful, sweeping, sophisticated recital piece for flute and harp.'
        },
        {
            id: 'MzCr-FBAE',
            category: 'music',
            subCategory: ['solo'],
            title: "Christmas Harpist", 
            artist_first: "Marylyn",
            artist_last: "Marzuki",
            price: '5.00',
            newprice: '', 
            condition: '6',
            level: 'Beg-Int',
            harptype: 'pedal',
            newprice: '12.95',
            notes: 'Some markings. Some yellowing from age.',
            image: "../../../img/store/findaharp/sheetmusic/christmasharpist.jpg", 
            description: "Beautiful Christmas arrangements for pedal harp."
        },
        {
            id: 'Pach-XWMJ',
            category: 'music', 
            subCategory: ['ensemble'],
            title: "Canon in D for harp solo or duet", 
            artist_first: "Johann",
            artist_last: "Pachelbel/Woods",
            price: '5.00', 
            newprice: '',
            condition: '8',
            level: 'Int',
            harptype: 'lever',
            notes: 'Like new. No markings.',
            image: "../../../img/store/findaharp/sheetmusic/canonind.jpg", 
            description: "Versatile arrangement of a classic. Can be played as a solo or with a 2nd harp or with flute or violin."
        },
        {
            id: 'Wald-PVBI',
            category: 'music', 
            subCategory: ['solo', 'pop'],
            title: "Tea at the Waldorf", 
            artist_first: "Ray",
            artist_last: "Pool",
            price: '13.50', 
            newprice: '19.50',
            condition: '10',
            level: 'Adv',
            harptype: 'Pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/Tea.jpg", 
            description: "Imaginative and enjoyable arrangements. A staple for the gigging harpist."
        },
        {
            id: 'West-JDXL',
            category: 'music', 
            subCategory: ['solo', 'pop'],
            title: "Into the West from Lord of the Rings", 
            artist_first: "Sylvia",
            artist_last: "Woods",
            price: '5.00', 
            newprice: '',
            condition: '8',
            level: 'Beg',
            harptype: 'lever',
            notes: 'A couple of markings. Otherwise excellent.',
            image: "../../../img/store/findaharp/sheetmusic/IntoWest.jpg", 
            description: "Easy and Intermediate versions. Beautiful melody."
        },
        {
            id: 'FrEx-DCUJ',
            category: 'music', 
            subcategory: ['solo', 'exercises'],
            title: "Harp Excercises for Speed and Agility", 
            artist_first: "Deborah",
            artist_last: "Friou",
            price: '12.00', 
            newprice: '',
            condition: '8',
            level: 'Int',
            harptype: 'lever',
            notes: 'A few markings. Otherwise excellent.',
            image: "../../../img/store/findaharp/sheetmusic/Agility.jpg", 
            description: "Excellent exercise book."
        },
        {
            id: 'Disw-NBSV',
            category: 'music', 
            subCategory: ['solo', 'pop'],
            title: "76 Disney Songs for the Harp", 
            artist_first: "Sylvia",
            artist_last: "Woods",
            price: '25.00', 
            newprice: '36.95',
            condition: '8',
            level: 'Int',
            harptype: 'lever',
            notes: 'A few markings. Otherwise excellent.',
            image: "../../../img/store/findaharp/sheetmusic/Disney.jpg", 
            description: "What a great book! Part of Your World, Be Our Guest, A Whole New World, Winnie the Pooh and many, many more."
        },
        {
            id: "CrWd-VONT",
            category: ['music'], 
            subCategory: ['Christmas'],
            title: "50 Christmas Carols for All Harps", 
            artist_first: "Sylvia",
            artist_last: "Woods",
            price: '13.00', 
            newprice: '19.95',
            condition: '9',
            level: 'beg-int',
            harptype: 'lever',
            notes: 'A couple of markings.',
            image: "../../../img/store/findaharp/sheetmusic/50Christmas.jpg", 
            description: "A must have for a gigging harpist. A fun book for a hobbyist. Each carol is arranged in an easy version and an intermediate version."
        },
        {
            id: "Cur3-SCYE",
            category: 'music', 
            subCategory: ['Instructional'],
            title: "Student Harpist, level 3", 
            artist_first: "Stephanie",
            artist_last: "Curcio",
            price: '6.00', 
            newprice: '12.00',
            condition: '7',
            level: 'Int-Adv',
            harptype: 'pedal',
            notes: 'Cover shows some age. Inside is like new.',
            image: "../../../img/store/findaharp/sheetmusic/Curcio3.jpg", 
            description: ""
        },
        {
            id: "Cur3-XCCX",
            category: 'music', 
            subCategory: ['Instructional'],
            title: "Student Harpist, level 2", 
            artist_first: "Stephanie",
            artist_last: "Curcio2",
            price: '3.00', 
            newprice: '12.00',
            condition: '3',
            level: 'Int-Adv',
            harptype: 'pedal',
            notes: 'Cover shows some age. Many markings inside. Some exercises completed.',
            image: "../../../img/store/findaharp/sheetmusic/Curcio2.jpg", 
            description: ""
        },
        {
            id: "RaFH-JVWR",
            category: 'music', 
            subCategory: ['instructional', 'collections'],
            title: "Making Music for Folk Harp", 
            artist_first: "Susan",
            artist_last: "Raimond",
            price: '9.00', 
            newprice: '14.99',
            condition: '10',
            level: 'beg',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/RaimondFH.jpg", 
            description: "Simple tunes for the Folk Harp. Comes with CD."
        },
        {
            id: "Rily-BUQU",
            category: 'music', 
            subCategory: ['instructional'],
            title: "Basic Harp for Beginners", 
            artist_first: "Laura",
            artist_last: "Riley",
            price: '10.00', 
            newprice: '14.99',
            condition: '10',
            level: 'beg',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/RileyBasicHarp.jpg", 
            description: "Instructional book starting from the very beginning."
        },
        {
            id: "RdCr-KZOH",
            category: 'music', 
            subCategory: ['Christmas','collection'],
            title: "A Carol Collection", 
            artist_first: "Mary",
            artist_last: "Radspinner",
            price: '2.00', 
            newprice: '5.00',
            condition: '9',
            level: 'int',
            harptype: 'all',
            notes: 'No markings. Like new.',
            image: "../../../img/store/findaharp/sheetmusic/Carols.jpg", 
            description: "6 Carols arranged for all harps."
        },
        {
            id: "WhLv-FCBA",
            category: 'music', 
            subCategory: ['solo','pop'],
            title: "Where is Love", 
            artist_first: "Carol",
            artist_last: "Robbins",
            price: '4.00', 
            newprice: '6.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new. Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/WhereLove.jpg", 
            description: ""
        },
        {
            id: "KlEx-ZHQN",
            category: 'music', 
            subCategory: ['instructional', 'excercises'],
            title: "20 Melodic Studies, vol 1, For All Harps", 
            artist_first: "Cindy",
            artist_last: "Kleinstuber",
            price: '3.00', 
            newprice: '',
            condition: '8',
            level: 'beg-int',
            harptype: 'all',
            notes: 'Some fading on the cover. Inside brand new.',
            image: "../../../img/store/findaharp/sheetmusic/Klein1.jpg", 
            description: "Reinforces basic techniques of intervals and arpeggios."
        },
        {
            id: "BtRb-LJZG",
            category: 'music', 
            subCategory: ['solo','pop'],
            title: "But Not For Me", 
            artist_first: "Carol",
            artist_last: "Robbins",
            price: '3.00', 
            newprice: '5.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/ButNotForMe.jpg", 
            description: "Jazzy, full chords, lots of pedals, but worth it!! Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper."
        },
        {
            id: "RnBw-TIGT",
            category: 'music', 
            subCategory: ['pop', 'pedal'],
            title: "I'm Always Chasing Rainbows", 
            artist_first: "Penny Howk",
            artist_last: "Beavers",
            price: '1.00', 
            newprice: '5.00',
            condition: '5',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Mistake in title on cover. Cover reads "Forever" instead of "Always". Inside like brand new. Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/Rainbows.jpg", 
            description: "An excellent arrangement."
        },
        {
            id: "BeWt-PRWK",
            category: 'music', 
            subCategory: ['pop'],
            title: "Bewitched", 
            artist_first: "Paul",
            artist_last: "Baker",
            price: '2.00', 
            newprice: '5.50',
            condition: '6',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Light smudges on cover. Inside like brand new. Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/Bewitched.jpg", 
            description: "Paul Baker is an excellent arranger."
        },
        {
            id: "MnRv-PPYT",
            category: 'music', 
            subCategory: ['pop', 'solo'],
            title: "Moon River", 
            artist_first: "Paul",
            artist_last: "Baker",
            price: '3.00', 
            newprice: '5.50',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/MoonRiver.jpg", 
            description: "Paul Baker is an excellent arranger!"
        },
        {
            id: "AnWz-GPVY",
            category: 'music', 
            subCategory: ['solo','pop'],
            title: "Anniversary Waltz", 
            artist_first: "Deborah",
            artist_last: "Henson-Conant",
            price: '1.00', 
            newprice: '4.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/AnniversaryWaltz.jpg", 
            description: ""
        },
        {
            id: "HdGv-OTUG",
            category: 'music', 
            subCategory: ['classical','solo'],
            title: "Gavotte from 'Semele'", 
            artist_first: "G.F.",
            artist_last: "Handel/Schuman",
            price: '3.00', 
            newprice: '',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/Gavotte.jpg", 
            description: "Arranged by Ellis Schuman."
        },
        {
            id: "FsPt-ZLME",
            category: 'music', 
            subCategory: ['solo','collections'],
            title: "Forest Pathways", 
            artist_first: "Dewey",
            artist_last: "Owens",
            price: '17.00', 
            newprice: '25.25',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/ForestPathways.jpg", 
            description: "A collection of Meditative Pieces arranged for pedal harp by Dewey Owens."
        },
        {
            id: "HnWh-MPIH",
            category: 'music', 
            subCategory: ['solo', 'wedding', 'classical'],
            title: "Where'er You Walk", 
            artist_first: "G.F.",
            artist_last: "Handel/Burton",
            price: '4.00', 
            newprice: '7.70',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/WhereWalk.jpg", 
            description: ""
        },
        {
            id: "HnPr-BTHA",
            category: 'music', 
            subCategory: ['classical','solo','wedding'],
            title: "Praise be to Thee", 
            artist_first: "G.F.",
            artist_last: "Handel",
            price: 'free with purchase', 
            newprice: '3.50',
            condition: '7',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Where on cover. Only 2 pages long.',
            image: "../../../img/store/findaharp/sheetmusic/PraiseBe.jpg", 
            description: ""
        },
        {
            id: "HnCr-SLOA",
            category: 'music', 
            subCategory: ['classical','wedding','solo'],
            title: "Two Sinfonias from 'Saul'", 
            artist_first: "G.F.",
            artist_last: "Handel/Schuman",
            price: '3.00', 
            newprice: '',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/SaulSinfonias.jpg", 
            description: ""
        },
        {
            id: "TrAr-JBOD",
            category: 'music', 
            subCategory: ['solo','folk'],
            title: "Three Traditional Airs", 
            artist_first: "Sheila",
            artist_last: "Larchet-Cuthbert",
            price: '3.00', 
            newprice: '',
            condition: '9',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Slight wear on cover. Inside brand new.',
            image: "../../../img/store/findaharp/sheetmusic/AncientAirs.jpg", 
            description: "Arranged by John F. Larchet. Transcribed for concert harp by Sheila Larchet Cuthbert."
        },
        {
            id: "RtSn-DHTK",
            category: 'music', 
            subCategory: ['classical','ensemble','fl/hp'],
            title: "Sonata", 
            artist_first: "Nino",
            artist_last: "Rota",
            price: '13.00', 
            newprice: '18.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/RotaSonata.jpg", 
            description: ""
        },
        {
            id: "RdSn-MLQG",
            category: 'music', 
            subCategory: ['concerto','classical'],
            title: "Concierto Serenata", 
            artist_first: "Joaquin",
            artist_last: "Rodrigo",
            price: '20.00', 
            newprice: '70.00',
            condition: '9',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Slight wear on cover. Like brand new inside. Amazon listed this new at $70.00, but might be a better new price elsewhere.',
            image: "../../../img/store/findaharp/sheetmusic/RodSeren.jpg", 
            description: ""
        },
        {
            id: "WrPd-BKXK",
            category: 'music', 
            subCategory: ['instructinoal'],
            title: "Writing for the Pedal Harp", 
            artist_first: "Ruth K.",
            artist_last: "Inglefield",
            price: '18.00', 
            newprice: '25.00',
            condition: '10',
            level: 'beg',
            harptype: 'pedal',
            notes: 'Like Brand New',
            image: "../../../img/store/findaharp/sheetmusic/InglefieldPedal.jpg", 
            description: "A Standardized Maual for Composers and Harpists"
        },
        {
            id: "SwGd-UAIV",
            category: 'music', 
            subCategory: ['instructinoal'],
            title: "Guide For Harpists", 
            artist_first: "Carl",
            artist_last: "Swanson",
            price: '9.00', 
            newprice: '16.00',
            condition: '7',
            level: 'beg',
            harptype: 'pedal',
            notes: 'Fading on the cover. No markings. Good inside.',
            image: "../../../img/store/findaharp/sheetmusic/SwansonGuide.jpg", 
            description: "An excellent resource."
        },
        {
            id: "BrCl-RDWF",
            category: 'music', 
            subCategory: ['pop', 'solo', 'collections'],
            title: "By Popular Demand, Favourite Standards", 
            artist_first: "Barbara",
            artist_last: "Brundage",
            price: '13.00', 
            newprice: '18.00',
            condition: '10',
            level: 'adv',
            harptype: 'lever',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/ByPopularStandards.jpg", 
            description: "Misty, Night and Day, Star Dust, and more"
        },
        {
            id: "PlPp-OXZH",
            category: 'music', 
            subCategory: ['pop','collections','solo'],
            title: "American Classic Pop, 12 Broadway Standards", 
            artist_first: "Ray",
            artist_last: "Pool",
            price: '18.00', 
            newprice: '24.00',
            condition: '10',
            level: 'adv',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/AmericanClassicPopBroadway.jpg", 
            description: "Love Walked In, My Funny Valentine, People and more"
        },
        {
            id: "PlPp-GYGL",
            category: 'music', 
            subCategory: ['pop','collections','solo'],
            title: "American Classic Pop, vol 2, Songs of George and Ira Gershwin", 
            artist_first: "Ray",
            artist_last: "Pool",
            price: '18.00', 
            newprice: '24.00',
            condition: '10',
            level: 'adv',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/AmericanClassicPop.jpg", 
            description: "But Not For Me, Embraceable You, I Got Rhythm, and more"
        },
        {
            id: "BrLv-HNLT",
            category: 'music', 
            subCategory: ['solo', 'collections'],
            title: "Popular Contemporary Love Songs for Harp", 
            artist_first: "Daniel",
            artist_last: "Burton",
            price: '7.00', 
            newprice: '11.00',
            condition: '10',
            level: 'int-adv',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/BurtonLove.jpg", 
            description: "Wind Beneath My Wings, The Rose, Evergreen, Sunrise Sunset"
        },
        {
            id: "GrBk-IFCH",
            category: 'music', 
            subCategory: ['ensemble', 'Fl/Hp/Vc','pop'],
            title: "A Gershwin Sampler", 
            artist_first: "George",
            artist_last: "Gershwin/Baker",
            price: '22.00', 
            newprice: '28.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/GershwinSampler.jpg", 
            description: "A medley of Gershwin tunes from Rhapsody in Blue, American in Paris, But Not For Me, Embraceable You, and more"
        },
        {
            id: "BWHK-PXWD",
            category: 'music', 
            subCategory: ['inspirational'],
            title: "Harp and the King, The", 
            artist_first: "Debbie",
            artist_last: "Brewin-Wilson",
            price: '5.00', 
            newprice: '',
            condition: '10',
            level: 'int',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/HarpofmyKing.jpg", 
            description: "Celtic tunes old and new for Christian Worship"
        },
        {
            id: "McHk-RIBZ",
            category: 'music', 
            subCategory: ['solo','classical','collections','instructional'],
            title: "Haiku for Harp", 
            artist_first: "Susann",
            artist_last: "McDonald/Linda Wood",
            price: '12.00', 
            newprice: '20.00',
            condition: '7',
            level: 'beg',
            harptype: 'pedal',
            notes: 'Some water marks on cover and first page. No markings. The rest is good.',
            image: "../../../img/store/findaharp/sheetmusic/Haiku.jpg", 
            description: "12 pieces that teach modern techniques such as pedal buzzes, fingernail glisses and changing meter."
        },
        {
            id: "MsFl-VTUC",
            category: 'music', 
            subCategory: ['ensemble', 'fl/hp','collections'],
            title: "Flute and Harp Delights, vol 1", 
            artist_first: "Patty",
            artist_last: "Masri-Fletcher",
            price: '6.50', 
            newprice: '13.00',
            condition: '7',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Upper right corner is bent. No markings. Inside excellent.',
            image: "../../../img/store/findaharp/sheetmusic/MasriV1.jpg", 
            description: "O Mio Bambino, The Swan, and more"
        },
        {
            id: "WtAn-OLQN",
            category: 'music', 
            subCategory: ['classical','solo','collections'],
            title: "Anthology of English Music for the Harp, vol. 1 1550-1650", 
            artist_first: "David",
            artist_last: "Watkins",
            price: '18.00', 
            newprice: '31.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/WatkinsV1.jpg", 
            description: "Farnaby, Morley, Byrd, Bull, and more"
        },
        {
            id: "ClTr-KVGM",
            category: 'music', 
            subCategory: ['pop','solo'],
            title: "Tears in Heaven", 
            artist_first: "Eric",
            artist_last: "Clapton",
            price: 'free with purchase', 
            newprice: '',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/Tears.jpg", 
            description: "NOT HARP MUSIC, piano/vocal/guitar"
        },
        {
            id: uuid(),
            category: 'accessories',
            title: "Test Item", 
            artist: "",
            harptype: "",
            price: '1.50',
            newprice: '',
            image: "../../../img/factoryFloor.jpg", 
            description: "This item is included for testing the strore functionality. Please choose credit card payment and use the following card: '4242 4242 4242 4242 exp. 04/24 CVC 242 zip 42424"
        },
    ]   


// template
// {
//     id: "-QRXP",
//     category: 'music', 
//     subCategory: [''],
//     title: "", 
//     artist_first: "",
//     artist_last: "",
//     price: '', 
//     newprice: '',
//     condition: '',
//     level: '',
//     harptype: '',
//     notes: '',
//     image: "../../../img/store/findaharp/sheetmusic/placeholder.jpg", 
//     description: ""
// },




export const FINDAHARP_PRODUCTSOLD = {   
    products_cds: [
        {
            id: "QAFT-WQDN",
            category: 'cd',
            subCategory: ['inspirational'],
            title: "A Quiet Afternoon", 
            artist_first: "Tisha",
            artist_last: "Murvihill",
            price: '15.00',
            image: "../../../img/store/findaharp/cds/QuietAfternoon.jpg", 
            description: "Winner, Instrumental Album of the Year, Gospel Music Association of Canada. Fourteen beautiful arrangements of some of our most beautiful worship melodies, including: I Exalt Thee; Oh, How He Loves You and Me; Fairest Lord Jesus; As the Deer; Jesus, Name Above All Names."
        },
        {
            id: 'BRWR-BIKF',
            category: 'cd', 
            subCategory: ['classical'],
            title: "If Brahms Wrote For Harp", 
            artist_first: "Tisha",
            artist_last: "Murvihill",
            price: 15.00,
            image: "../../../img/store/findaharp/cds/IfBrahmsWrote.jpg", 
            description: "“Stunning Presentation of the music of Johannes Brahms” - The HarpColumn - Eleven Intermezzi and a Rhapsody Arranged and performed by Tisha Murvihill, Calgary Philharmonic Orchestra Principal Harp."
        },
        {
            id: 'JustAs-NUAA',
            category: 'cd', 
            title: "Come Just As You Are", 
            subCategory: ['inspirational'], 
            artist_first: "Tisha",
            artist_last: "Murvihill",
            price: 15.00,
            image: "../../../img/store/findaharp/cds/ComeJustAs.webp", 
            description: "Come Just As You Are is a follow-up CD to Tisha’s award winning CD, A Quiet Afternoon. The CD features 14 inspirational praise and worship songs including Amazing Grace, Draw Me Close to You, Lord Be Glorified, and You Are My All in All."
        },
    ],  
    products_music: [
        {
            id: "VNHP-ZBYT",
            artist_first: 'Gioachino',
            artist_last: 'Rossini',
            category: 'music',
            subCategory: ['ensemble'],
            title: "Andante con Variationi for violin and harp", 
            price: 3.00, 
            newprice: '',
            condition: '7',
            level: 'Adv',
            harptype: 'Pedal',
            notes: 'Some yellowing around edges. No markings.',
            image: "../../../img/store/findaharp/sheetmusic/rossiniandante.jpg", 
            description: "edited by Amedeo Cerasa."
        },
        {
            id: 'RVVC-XIUY',
            category: 'music',
            subCategory: ['ensemble'],
            title: "5 Popular Greek Melodies for voice and harp", 
            artist_first: "Maurice",
            artist_last: "Ravel/Salzedo",
            price: '7.00', 
            newprice: '',
            condition: '9',
            level: 'Adv',
            harptype: 'pedal',
            newprice: '15.00',
            notes: 'Good shape. No markings. Small water mark in upper l.h. corner.',
            image: "../../../img/store/findaharp/sheetmusic/ravelgreek.jpg", 
            description: "A hidden gem. Rarely played, stunning work by Ravel. 5 short melodies from the folk tradition."
        },
        {
            id: 'KrFl-TPNQ',
            category: 'music',
            subCategory: ['ensemble'], 
            title: "Sonata No. III for flute (or violin) and harp", 
            artist_first: "Jean-Baptiste",
            artist_last: "Krumpholz/Avesian",
            price: '7.00', 
            newprice: '',
            condition: '10',
            level: 'Int-Adv',
            harptype: 'Pedal',
            newprice: '14.00',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/krumpholzsonata3.jpg", 
            description: "Great for setting a classical, sophisticated atmosphere."
        },
        {
            id: 'WdQn-AFNR',
            category: 'music',
            subCategory: ['ensemble'], 
            title: "Three Wedding Marches for woodwind quintet and harp.", 
            artist_first: "",
            artist_last: "Wagner, Mozart, Mendelssohn",
            price: '10.00', 
            newprice: '',
            condition: '9',
            level: 'Int',
            harptype: 'lever',
            newprice: '25.00',
            notes: 'Like brand new inside. Slightly worn on cover (see photo).',
            image: "../../../img/store/findaharp/sheetmusic/weddingmarchesquintet.jpg", 
            description: 'Mozart, March from "Marriage of Figaro"; Wagner, Bridal Chorus from "Lohengrin" (Here Comes the Bride); Mendelssohn, Wedding March from "A Mid-Summer Nights Dream". Arranged by Ryohel Nakagawa.'
        },
        {
            id: 'HovA-KZXD',
            category: 'music',
            subCategory: ['ensemble'], 
            title: "Garden of Adonis for flute and harp (or piano)", 
            artist_first: "Alan",
            artist_last: "Hovaness",
            price: '13.00', 
            newprice: '',
            condition: '7',
            level: 'Adv',
            harptype: 'Pedal',
            newprice: '25.00',
            notes: 'A few markings in harp part. Many markings in flute part. Otherwise excellent condition.',
            image: "../../../img/store/findaharp/sheetmusic/hovanessadonis.jpg", 
            description: 'Beautiful, sweeping, sophisticated recital piece for flute and harp.'
        },
        {
            id: 'MzCr-FBAE',
            category: 'music',
            subCategory: ['solo'],
            title: "Christmas Harpist", 
            artist_first: "Marylyn",
            artist_last: "Marzuki",
            price: '5.00',
            newprice: '', 
            condition: '6',
            level: 'Beg-Int',
            harptype: 'pedal',
            newprice: '12.95',
            notes: 'Some markings. Some yellowing from age.',
            image: "../../../img/store/findaharp/sheetmusic/christmasharpist.jpg", 
            description: "Beautiful Christmas arrangements for pedal harp."
        },
        {
            id: 'Pach-XWMJ',
            category: 'music', 
            subCategory: ['ensemble'],
            title: "Canon in D for harp solo or duet", 
            artist_first: "Johann",
            artist_last: "Pachelbel/Woods",
            price: '5.00', 
            newprice: '',
            condition: '8',
            level: 'Int',
            harptype: 'lever',
            notes: 'Like new. No markings.',
            image: "../../../img/store/findaharp/sheetmusic/canonind.jpg", 
            description: "Versatile arrangement of a classic. Can be played as a solo or with a 2nd harp or with flute or violin."
        },
        {
            id: 'Wald-PVBI',
            category: 'music', 
            subCategory: ['solo', 'pop'],
            title: "Tea at the Waldorf", 
            artist_first: "Ray",
            artist_last: "Pool",
            price: '13.50', 
            newprice: '19.50',
            condition: '10',
            level: 'Adv',
            harptype: 'Pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/Tea.jpg", 
            description: "Imaginative and enjoyable arrangements. A staple for the gigging harpist."
        },
        {
            id: 'West-JDXL',
            category: 'music', 
            subCategory: ['solo', 'pop'],
            title: "Into the West from Lord of the Rings", 
            artist_first: "Sylvia",
            artist_last: "Woods",
            price: '5.00', 
            newprice: '',
            condition: '8',
            level: 'Beg',
            harptype: 'lever',
            notes: 'A couple of markings. Otherwise excellent.',
            image: "../../../img/store/findaharp/sheetmusic/IntoWest.jpg", 
            description: "Easy and Intermediate versions. Beautiful melody."
        },
        {
            id: 'FrEx-DCUJ',
            category: 'music', 
            subcategory: ['solo', 'exercises'],
            title: "Harp Excercises for Speed and Agility", 
            artist_first: "Deborah",
            artist_last: "Friou",
            price: '12.00', 
            newprice: '',
            condition: '8',
            level: 'Int',
            harptype: 'lever',
            notes: 'A few markings. Otherwise excellent.',
            image: "../../../img/store/findaharp/sheetmusic/Agility.jpg", 
            description: "Excellent exercise book."
        },
        {
            id: 'Disw-NBSV',
            category: 'music', 
            subCategory: ['solo', 'pop'],
            title: "76 Disney Songs for the Harp", 
            artist_first: "Sylvia",
            artist_last: "Woods",
            price: '25.00', 
            newprice: '36.95',
            condition: '8',
            level: 'Int',
            harptype: 'lever',
            notes: 'A few markings. Otherwise excellent.',
            image: "../../../img/store/findaharp/sheetmusic/Disney.jpg", 
            description: "What a great book! Part of Your World, Be Our Guest, A Whole New World, Winnie the Pooh and many, many more."
        },
        {
            id: "CrWd-VONT",
            category: ['music'], 
            subCategory: ['Christmas'],
            title: "50 Christmas Carols for All Harps", 
            artist_first: "Sylvia",
            artist_last: "Woods",
            price: '13.00', 
            newprice: '19.95',
            condition: '9',
            level: 'beg-int',
            harptype: 'lever',
            notes: 'A couple of markings.',
            image: "../../../img/store/findaharp/sheetmusic/50Christmas.jpg", 
            description: "A must have for a gigging harpist. A fun book for a hobbyist. Each carol is arranged in an easy version and an intermediate version."
        },
        {
            id: "Cur3-SCYE",
            category: 'music', 
            subCategory: ['Instructional'],
            title: "Student Harpist, level 3", 
            artist_first: "Stephanie",
            artist_last: "Curcio",
            price: '6.00', 
            newprice: '12.00',
            condition: '7',
            level: 'Int-Adv',
            harptype: 'pedal',
            notes: 'Cover shows some age. Inside is like new.',
            image: "../../../img/store/findaharp/sheetmusic/Curcio3.jpg", 
            description: ""
        },
        {
            id: "Cur3-XCCX",
            category: 'music', 
            subCategory: ['Instructional'],
            title: "Student Harpist, level 2", 
            artist_first: "Stephanie",
            artist_last: "Curcio2",
            price: '3.00', 
            newprice: '12.00',
            condition: '3',
            level: 'Int-Adv',
            harptype: 'pedal',
            notes: 'Cover shows some age. Many markings inside. Some exercises completed.',
            image: "../../../img/store/findaharp/sheetmusic/Curcio2.jpg", 
            description: ""
        },
        {
            id: "RaFH-JVWR",
            category: 'music', 
            subCategory: ['instructional', 'collections'],
            title: "Making Music for Folk Harp", 
            artist_first: "Susan",
            artist_last: "Raimond",
            price: '9.00', 
            newprice: '14.99',
            condition: '10',
            level: 'beg',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/RaimondFH.jpg", 
            description: "Simple tunes for the Folk Harp. Comes with CD."
        },
        {
            id: "Rily-BUQU",
            category: 'music', 
            subCategory: ['instructional'],
            title: "Basic Harp for Beginners", 
            artist_first: "Laura",
            artist_last: "Riley",
            price: '10.00', 
            newprice: '14.99',
            condition: '10',
            level: 'beg',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/RileyBasicHarp.jpg", 
            description: "Instructional book starting from the very beginning."
        },
        {
            id: "RdCr-KZOH",
            category: 'music', 
            subCategory: ['Christmas','collection'],
            title: "A Carol Collection", 
            artist_first: "Mary",
            artist_last: "Radspinner",
            price: '2.00', 
            newprice: '5.00',
            condition: '9',
            level: 'int',
            harptype: 'all',
            notes: 'No markings. Like new.',
            image: "../../../img/store/findaharp/sheetmusic/Carols.jpg", 
            description: "6 Carols arranged for all harps."
        },
        {
            id: "WhLv-FCBA",
            category: 'music', 
            subCategory: ['solo','pop'],
            title: "Where is Love", 
            artist_first: "Carol",
            artist_last: "Robbins",
            price: '4.00', 
            newprice: '6.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new. Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/WhereLove.jpg", 
            description: ""
        },
        {
            id: "KlEx-ZHQN",
            category: 'music', 
            subCategory: ['instructional', 'excercises'],
            title: "20 Melodic Studies, vol 1, For All Harps", 
            artist_first: "Cindy",
            artist_last: "Kleinstuber",
            price: '3.00', 
            newprice: '',
            condition: '8',
            level: 'beg-int',
            harptype: 'all',
            notes: 'Some fading on the cover. Inside brand new.',
            image: "../../../img/store/findaharp/sheetmusic/Klein1.jpg", 
            description: "Reinforces basic techniques of intervals and arpeggios."
        },
        {
            id: "BtRb-LJZG",
            category: 'music', 
            subCategory: ['solo','pop'],
            title: "But Not For Me", 
            artist_first: "Carol",
            artist_last: "Robbins",
            price: '3.00', 
            newprice: '5.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/ButNotForMe.jpg", 
            description: "Jazzy, full chords, lots of pedals, but worth it!! Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper."
        },
        {
            id: "RnBw-TIGT",
            category: 'music', 
            subCategory: ['pop', 'pedal'],
            title: "I'm Always Chasing Rainbows", 
            artist_first: "Penny Howk",
            artist_last: "Beavers",
            price: '1.00', 
            newprice: '5.00',
            condition: '5',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Mistake in title on cover. Cover reads "Forever" instead of "Always". Inside like brand new. Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/Rainbows.jpg", 
            description: "An excellent arrangement."
        },
        {
            id: "BeWt-PRWK",
            category: 'music', 
            subCategory: ['pop'],
            title: "Bewitched", 
            artist_first: "Paul",
            artist_last: "Baker",
            price: '2.00', 
            newprice: '5.50',
            condition: '6',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Light smudges on cover. Inside like brand new. Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/Bewitched.jpg", 
            description: "Paul Baker is an excellent arranger."
        },
        {
            id: "MnRv-PPYT",
            category: 'music', 
            subCategory: ['pop', 'solo'],
            title: "Moon River", 
            artist_first: "Paul",
            artist_last: "Baker",
            price: '3.00', 
            newprice: '5.50',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/MoonRiver.jpg", 
            description: "Paul Baker is an excellent arranger!"
        },
        {
            id: "AnWz-GPVY",
            category: 'music', 
            subCategory: ['solo','pop'],
            title: "Anniversary Waltz", 
            artist_first: "Deborah",
            artist_last: "Henson-Conant",
            price: '1.00', 
            newprice: '4.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Vanderbilt Editions has designed their pop music to put in gig books, loose leaf on hard stock paper.',
            image: "../../../img/store/findaharp/sheetmusic/AnniversaryWaltz.jpg", 
            description: ""
        },
        {
            id: "HdGv-OTUG",
            category: 'music', 
            subCategory: ['classical','solo'],
            title: "Gavotte from 'Semele'", 
            artist_first: "G.F.",
            artist_last: "Handel/Schuman",
            price: '3.00', 
            newprice: '',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/Gavotte.jpg", 
            description: "Arranged by Ellis Schuman."
        },
        {
            id: "FsPt-ZLME",
            category: 'music', 
            subCategory: ['solo','collections'],
            title: "Forest Pathways", 
            artist_first: "Dewey",
            artist_last: "Owens",
            price: '17.00', 
            newprice: '25.25',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/ForestPathways.jpg", 
            description: "A collection of Meditative Pieces arranged for pedal harp by Dewey Owens."
        },
        {
            id: "HnWh-MPIH",
            category: 'music', 
            subCategory: ['solo', 'wedding', 'classical'],
            title: "Where'er You Walk", 
            artist_first: "G.F.",
            artist_last: "Handel/Burton",
            price: '4.00', 
            newprice: '7.70',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/WhereWalk.jpg", 
            description: ""
        },
        {
            id: "HnPr-BTHA",
            category: 'music', 
            subCategory: ['classical','solo','wedding'],
            title: "Praise be to Thee", 
            artist_first: "G.F.",
            artist_last: "Handel",
            price: 'free with purchase', 
            newprice: '3.50',
            condition: '7',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Where on cover. Only 2 pages long.',
            image: "../../../img/store/findaharp/sheetmusic/PraiseBe.jpg", 
            description: ""
        },
        {
            id: "HnCr-SLOA",
            category: 'music', 
            subCategory: ['classical','wedding','solo'],
            title: "Two Sinfonias from 'Saul'", 
            artist_first: "G.F.",
            artist_last: "Handel/Schuman",
            price: '3.00', 
            newprice: '',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/SaulSinfonias.jpg", 
            description: ""
        },
        {
            id: "TrAr-JBOD",
            category: 'music', 
            subCategory: ['solo','folk'],
            title: "Three Traditional Airs", 
            artist_first: "Sheila",
            artist_last: "Larchet-Cuthbert",
            price: '3.00', 
            newprice: '',
            condition: '9',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Slight wear on cover. Inside brand new.',
            image: "../../../img/store/findaharp/sheetmusic/AncientAirs.jpg", 
            description: "Arranged by John F. Larchet. Transcribed for concert harp by Sheila Larchet Cuthbert."
        },
        {
            id: "RtSn-DHTK",
            category: 'music', 
            subCategory: ['classical','ensemble','fl/hp'],
            title: "Sonata", 
            artist_first: "Nino",
            artist_last: "Rota",
            price: '13.00', 
            newprice: '18.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/RotaSonata.jpg", 
            description: ""
        },
        {
            id: "RdSn-MLQG",
            category: 'music', 
            subCategory: ['concerto','classical'],
            title: "Concierto Serenata", 
            artist_first: "Joaquin",
            artist_last: "Rodrigo",
            price: '20.00', 
            newprice: '70.00',
            condition: '9',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Slight wear on cover. Like brand new inside. Amazon listed this new at $70.00, but might be a better new price elsewhere.',
            image: "../../../img/store/findaharp/sheetmusic/RodSeren.jpg", 
            description: ""
        },
        {
            id: "WrPd-BKXK",
            category: 'music', 
            subCategory: ['instructinoal'],
            title: "Writing for the Pedal Harp", 
            artist_first: "Ruth K.",
            artist_last: "Inglefield",
            price: '18.00', 
            newprice: '25.00',
            condition: '10',
            level: 'beg',
            harptype: 'pedal',
            notes: 'Like Brand New',
            image: "../../../img/store/findaharp/sheetmusic/InglefieldPedal.jpg", 
            description: "A Standardized Maual for Composers and Harpists"
        },
        {
            id: "SwGd-UAIV",
            category: 'music', 
            subCategory: ['instructinoal'],
            title: "Guide For Harpists", 
            artist_first: "Carl",
            artist_last: "Swanson",
            price: '9.00', 
            newprice: '16.00',
            condition: '7',
            level: 'beg',
            harptype: 'pedal',
            notes: 'Fading on the cover. No markings. Good inside.',
            image: "../../../img/store/findaharp/sheetmusic/SwansonGuide.jpg", 
            description: "An excellent resource."
        },
        {
            id: "BrCl-RDWF",
            category: 'music', 
            subCategory: ['pop', 'solo', 'collections'],
            title: "By Popular Demand, Favourite Standards", 
            artist_first: "Barbara",
            artist_last: "Brundage",
            price: '13.00', 
            newprice: '18.00',
            condition: '10',
            level: 'adv',
            harptype: 'lever',
            notes: 'Like brand new.',
            image: "../../../img/store/findaharp/sheetmusic/ByPopularStandards.jpg", 
            description: "Misty, Night and Day, Star Dust, and more"
        },
        {
            id: "PlPp-OXZH",
            category: 'music', 
            subCategory: ['pop','collections','solo'],
            title: "American Classic Pop, 12 Broadway Standards", 
            artist_first: "Ray",
            artist_last: "Pool",
            price: '18.00', 
            newprice: '24.00',
            condition: '10',
            level: 'adv',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/AmericanClassicPopBroadway.jpg", 
            description: "Love Walked In, My Funny Valentine, People and more"
        },
        {
            id: "PlPp-GYGL",
            category: 'music', 
            subCategory: ['pop','collections','solo'],
            title: "American Classic Pop, vol 2, Songs of George and Ira Gershwin", 
            artist_first: "Ray",
            artist_last: "Pool",
            price: '18.00', 
            newprice: '24.00',
            condition: '10',
            level: 'adv',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/AmericanClassicPop.jpg", 
            description: "But Not For Me, Embraceable You, I Got Rhythm, and more"
        },
        {
            id: "BrLv-HNLT",
            category: 'music', 
            subCategory: ['solo', 'collections'],
            title: "Popular Contemporary Love Songs for Harp", 
            artist_first: "Daniel",
            artist_last: "Burton",
            price: '7.00', 
            newprice: '11.00',
            condition: '10',
            level: 'int-adv',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/BurtonLove.jpg", 
            description: "Wind Beneath My Wings, The Rose, Evergreen, Sunrise Sunset"
        },
        {
            id: "GrBk-IFCH",
            category: 'music', 
            subCategory: ['ensemble', 'Fl/Hp/Vc','pop'],
            title: "A Gershwin Sampler", 
            artist_first: "George",
            artist_last: "Gershwin/Baker",
            price: '22.00', 
            newprice: '28.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/GershwinSampler.jpg", 
            description: "A medley of Gershwin tunes from Rhapsody in Blue, American in Paris, But Not For Me, Embraceable You, and more"
        },
        {
            id: "BWHK-PXWD",
            category: 'music', 
            subCategory: ['inspirational'],
            title: "Harp and the King, The", 
            artist_first: "Debbie",
            artist_last: "Brewin-Wilson",
            price: '5.00', 
            newprice: '',
            condition: '10',
            level: 'int',
            harptype: 'lever',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/HarpofmyKing.jpg", 
            description: "Celtic tunes old and new for Christian Worship"
        },
        {
            id: "McHk-RIBZ",
            category: 'music', 
            subCategory: ['solo','classical','collections','instructional'],
            title: "Haiku for Harp", 
            artist_first: "Susann",
            artist_last: "McDonald/Linda Wood",
            price: '12.00', 
            newprice: '20.00',
            condition: '7',
            level: 'beg',
            harptype: 'pedal',
            notes: 'Some water marks on cover and first page. No markings. The rest is good.',
            image: "../../../img/store/findaharp/sheetmusic/Haiku.jpg", 
            description: "12 pieces that teach modern techniques such as pedal buzzes, fingernail glisses and changing meter."
        },
        {
            id: "MsFl-VTUC",
            category: 'music', 
            subCategory: ['ensemble', 'fl/hp','collections'],
            title: "Flute and Harp Delights, vol 1", 
            artist_first: "Patty",
            artist_last: "Masri-Fletcher",
            price: '6.50', 
            newprice: '13.00',
            condition: '7',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Upper right corner is bent. No markings. Inside excellent.',
            image: "../../../img/store/findaharp/sheetmusic/MasriV1.jpg", 
            description: "O Mio Bambino, The Swan, and more"
        },
        {
            id: "WtAn-OLQN",
            category: 'music', 
            subCategory: ['classical','solo','collections'],
            title: "Anthology of English Music for the Harp, vol. 1 1550-1650", 
            artist_first: "David",
            artist_last: "Watkins",
            price: '18.00', 
            newprice: '31.00',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/WatkinsV1.jpg", 
            description: "Farnaby, Morley, Byrd, Bull, and more"
        },
        {
            id: "ClTr-KVGM",
            category: 'music', 
            subCategory: ['pop','solo'],
            title: "Tears in Heaven", 
            artist_first: "Eric",
            artist_last: "Clapton",
            price: 'free with purchase', 
            newprice: '',
            condition: '10',
            level: 'adv',
            harptype: 'pedal',
            notes: 'Like brand new',
            image: "../../../img/store/findaharp/sheetmusic/Tears.jpg", 
            description: "NOT HARP MUSIC, piano/vocal/guitar"
        }
    ]   
}

// template
// {
//     id: "-QRXP",
//     category: 'music', 
//     subCategory: [''],
//     title: "", 
//     artist_first: "",
//     artist_last: "",
//     price: '', 
//     newprice: '',
//     condition: '',
//     level: '',
//     harptype: '',
//     notes: '',
//     image: "../../../img/store/findaharp/sheetmusic/placeholder.jpg", 
//     description: ""
// },
