export const ABBR = [
    ['Bow Brand Pedal Gut','BB Pedal Gut'],
    ['Bow Brand Lever Gut','BB Lever Gut'],
    ['Concedo Gut','Concedo Gut'],
    ['Burgundy Gut','Burgundy Gut'],
    ['Silkgut (synthetic)','Silkgut'],
    ['Bow Brand Nylon','BB Nylon'],
    ['Artist Nylon','Artist Nylon'],
    ['Nylon Monofilament','Nylon Monofil'],
    ['Wire String Sets','Wire Sets'],
    ['Silver-Plated Pedal Bass Wires','Silver Wires'],
    ['Tarnish-Resistant Pedal Bass Wires','Tarn-Res Wires'],
    ['Bow Brand Lever Bass Wires','BB Lever Wires'],
    ['Professional Lever Bass Wires','Pro Lever Wires'],
    ['Savarez KF Composite','Savarez'],
    ["FH Models", 'FH Models'],
    ["Ravenna", 'Ravenna'],
    ["Allegro", 'Allegro'],
    ["Crescendo", 'Crescendo'],
    ["Aberdeen Meadows A to A", 'Aber Mead A-A'],
    ["Aberdeen Meadows C to C", 'Aber Mead C-C'],
    ["Glen Aulin", 'Glen Aulin'],
    ["Grand Harpsicle", 'Grand Harpsicle'],
    ["Logan Meadow", 'Logan Mead'],
    ["Mirror Meadows", 'Mirror Mead'],
    ["Tuolumne Meadow", 'Tuolumne Mead'],
    ["Tasty 29", 'Tasty 29'],
    ["Mariposa A to C", 'Mari A-C'],
    ["Mariposa F to A", 'Mari F-A'],
    ["Shaylee Meadows", 'Shaylee Mead'],
    ["Special Edition Fullsicle", 'Sp Ed Fullsicle'],
    ["Salvi Delta", 'Delta'],
    ["Anne",'Anne'],
    ["Braunwen",'Braunwen'],
    ["Briar Rose",'Briar Rose'],
    ["Even Song",'Even Song'],
    ["Lorraine",'Lorraine'],
    ["Marion",'Marion'],
    ["Sara",'Sara'],
    ["Nino 30",'Nino 30'],
    ["Sierra 30",'Sierra 30'],
    ["Sierra 34",'Sierra 34'],
    ["Sierra 36",'Sierra 36'],
    ["Catalina",'Catalina'],
    ["Signature",'Signature'],
    ["Eclipse",'Eclipse'],
    ["Christina Therapy",'Christina'],
    ["30 Wire",'30 Wire'],
    ["33 Wire Excelle II",'33 Excelle II'],
    ["35 Wire Luna",'35 Luna'],
    ["Avalon",'Avalon'],
    ["McCall 25",'McCall 25'],
    ["Axline",'Axline'],
    ["Celtic",'Celtic'],
    ["Nova",'Nova'],
    ["Briggs 34",'Briggs 34'],
    ["Premiere 38",'Premiere 38'],
    ["Nylon 30",'Nylon 30'],
    ["Shanti 28",'Shanti 28'],
    ["Lever Solos",'Lever Solos'],
    ["Lever Solo Collections",'Lever Solo Collect'],
    ["Lever Ensemble",'Lever Ensemble'],
    ["Lever with Other Instruments",'Lever w/Ins'],
    ["Lever with Voice or Chorus",'Lever w/Vc'],
    ["Lever Methods and Studies",'Lever Methods'],
    ["Lever Holiday",'Lever Holiday'],
    ["Lever Popular Solos and Collections",'Lever Pop'],
    ["Pedal Solos",'Pedal Solos'],
    ["Pedal Solo Collections",'Pedal Solo Collect'],
    ["Pedal Ensemble",'Pedal Ensemble'],
    ["Pedal with Flute",'Pedal w/Fl'],
    ["Pedal with Other Instruments",'Pedal w/Ins'],
    ["Pedal with Voice or Chorus",'Pedal w/Vc'],
    ["Pedal Methods and Studies",'Pedal Methods'],
    ["Pedal Concertos",'Pedal Concertos'],
    ["Pedal Orchestra Parts",'Pedal Orch Parts'],
    ["Pedal Holiday",'Pedal Holiday'],
    ["Pedal Popular Solos and Collections",'Pedal Pop'],
    ["Covers", 'Covers'],
    ["Electronics", 'Electronics'],
    ["Harp Care", 'Harp Care'],
    ["Transportation", 'Transportation'],
    ["Tuning Keys", 'Tuning Keys'],
    ["Music Stands", 'Music Stands'],
    ["Crowns", 'Crowns'],
    ["For Students", 'For Students'],
    ["Biographical Books", 'Biographies'],
    ["Instructional Books", 'Instruction Bks'],
    ["Gifts", 'Gifts'],
    ["Gift Certificates", 'Gift Cert'],
    ["Classical", 'Cds-Classical'],
    ["Inspirational", 'Cds-Inspiration'],
    ["Other", 'Cds-Other']
]